name: screenify
description: A Flutter app for Screens
# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  font_awesome_flutter: ^8.8.1
  google_fonts: ^1.1.0
  line_awesome_flutter: ^1.0.1
  path_provider: ^1.6.18
  percent_indicator: ^2.1.5
  marquee: ^1.5.2
  cool_alert: ^1.0.1
  badges: ^1.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: OCR
      fonts:
        - asset: fonts/OCR_A_Regular.ttf

  assets:
    - assets/images/
    - assets/images/homescreens/
    - assets/images/loginscreens/
    - assets/images/profilescreens/
    - assets/images/bottomsheetscreens/

    #      <--------------------------  Add HomeScreen related sub-folders here --------------------------->

    - assets/images/homescreens/fitnessapp/
    - assets/images/homescreens/muziko/
    - assets/images/homescreens/shoppingScreen/



    #      <--------------------------  Add LoginScreen related sub-folders here --------------------------->

    - assets/images/loginscreens/muziko/
    - assets/images/loginscreens/purvikrana/

    #      <--------------------------  Add ProfileScreen related sub-folders here --------------------------->

    - assets/images/profilescreens/designerportfolio/

    #      <--------------------------  Add BottomSheet screen related sub-folders here --------------------------->

    - assets/images/bottomsheetscreens/quickpay/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
